--- a/Kbuild	2025-04-04 23:56:58.970661493 +0300
+++ a/Kbuild	2025-04-05 00:00:11.178846096 +0300
@@ -1,8 +1,6 @@
 xone-wired-y := transport/wired.o
-xone-dongle-y := transport/dongle.o transport/mt76.o
 xone-gip-y := bus/bus.o bus/protocol.o driver/common.o
 xone-gip-gamepad-y := driver/gamepad.o
-xone-gip-headset-y := driver/headset.o
 xone-gip-chatpad-y := driver/chatpad.o
 xone-gip-guitar-y := driver/guitar.o
-obj-m := xone-wired.o xone-dongle.o xone-gip.o xone-gip-gamepad.o xone-gip-headset.o xone-gip-chatpad.o xone-gip-guitar.o
+obj-m := xone-wired.o xone-gip.o xone-gip-gamepad.o xone-gip-chatpad.o xone-gip-guitar.o
